notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: j9c233rgd/s2OqerF7TXAYo1RkQTdHcvprjD8MvxdnWyjvN/bDYnlB/nj9MSxASZvyLljnuj0Sn7k7tmSlaZc9kG/YcL0e/4PXiyHv0BBlk8jeNJI2wXwthCt2/969593Z1MYgow0prz7qlDIzRkYwvSGles4pprBSghFFSBWHtfIrUfzxKk1U+ekaMOw4eNc9B1Da6DVaKV9VYnVzqIVJhsNhOKjkaYRzb73IbSdq2wTmmR94cvB4RYN1NDGTMiWfHzKuq37LMhN3CtyiiyeV19Svl4oxehe27iCnXnILGiph7t5xNsBRm71McDzQ4IK1HVdfieGW3cW8prhyA6o5fjZ7YxaQDfppSZE0YMyetWYKgn/VKUr3QNlAq7or+IoUSDhktRzqviUqp7mVk8kNXQTDc/t+CvJK2zze1lAmxfXxWoa+Bo/hpU7nXmko7dKQRWCOVEoBVTkC/UokFUvPs2JQUN018CXk0Pd++fQeJl/xZcPAWT9WhN70V2PeS1mmwfz9TwfH0D8ly3dqfz9yB55M54ZIXcPuB9mUDBPQ3hfnNx/0msDYBzZ1ZjS5hqz4gvt31tkYOWUkcwR278lV4/JJTgHXpwwwNHvJoh0DDcsUpiB1Q9/vWEw8OyjXL3ZFaG+x+dT5Vq4jVou5sMkivRDKxYqusBqfAn76z7m74=
  api_key:
    secure: JQijAFKbU/2tjDnt3SZUuDaJoyd8ILxY27G936yePLlKf9JqDTnUHXiSgFv4gXMJm03TuuHA3Ew300MTuIzIEWx20Rw6Vofwq3J3B11J+gCx9pnWdsW/rG+2PReO9Xqshz9rhF5XONFWbBADQDLDv5mUody0VPD3EJ0s+PZxFSWYnYghk8mTED0/XbC7ctbP3xWmcfpXpFCS4ZNkg9NX/fXNyE/Zhez55Ju1d6ph6vGbVdntKaQCkb8QkWqza9P41Yf6cDXb1tXh5BvWkGzbc/oPhqRPfNF5EMmPTS9Tgrqw1YBG2Lm8KP+M13XKEPEm/uKJDY19bYaNrB+AASr/XVjFtxaoDYWRFi1wE02mOZPosMAtC/rI83S3gd5PN/GvClpzev0IIjwwKVR71IydFdrR804bxA5TLamPPtXYMQawPUZHWG9YgdL0R5wPvG1T+nDiN7Bts1/WZhDvJBf8Xpsyt4eNe6IqOEfX1xeQ88ebjL3wcpekmQIY87TT8H9ajV26br7EXlUw5DpbCLWGApJG39oot/lpE6LuydmdEWyEbQrJ4iwx5FX3HOHRxzWj2WfGpS31B9xQ6GBAzryP847KqsFsMGdIF2bpxBrgEQPoaeukyRSsFLkmkkZlZ/HJ/Jy956REUxLQkUesLZ6Pls16J2ZqDs/z75L6PQB2voA=
  on:
    tags: true
